version: '3'
services:
  core:
    build: ./stellar-core
    environment:
      - DATABASE_URL=dbname=core host=docker.for.mac.localhost user=gzigzigzeo
      - NETWORK=pubnet
    ports:
      - "11625:11625"
      - "11626:11626"
    volumes:
      - ./.data:/var/stellar-core

  horizon:
    build: ./stellar-horizon
    depends_on:
      - "core"
    environment:
      - STELLAR_CORE_DATABASE_URL=postgres://gzigzigzeo@docker.for.mac.localhost/core?sslmode=disable
      - DATABASE_URL=postgres://gzigzigzeo@docker.for.mac.localhost/horizon?sslmode=disable
      - STELLAR_CORE_URL=http://core:11626
    ports:
      - "8000:8000"
