version: '3'
services:
  core:
    build: ./core
    env_file: ./.env
    ports:
      - "11625:11625"
      - "11626:11626"
    healthcheck:
      test: "CMD /healthcheck.sh"
    restart: unless-stopped
    volumes:
      - ./.data/stellar-core:/var/stellar-core
      - ./.log/stellar-core:/var/log/stellar-core
    networks:
      - core

  horizon:
    build: ./horizon
    env_file: ./.env
    depends_on:
      - "core"
    healthcheck:
      test: "CMD /healthcheck.sh"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - core
      - horizon

  eth:
    image: ethereum/client-go
    env_file: ./.env
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./.data/eth/.etherum:/root/.etherum
      - ./.data/eth/.ethash:/root/.ethash
    entrypoint: geth -${NETWORK}

  btc:
    env_file: ./.env
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
    volumes:
      - "./.data/btc:/home/bitcoin/.bitcoin"
    image: amacneil/bitcoin
    command: bitcoind -testnet

  bifrost:
    env_file: ./.env
    build: ./bifrost
    ports:
      - "9000:9000"
    depends_on:
      - core
      - horizon
      - eth
      - btc

networks:
  core:
  horizon:
