version: '3'

services:
#  core:
#    build: ./core
#    env_file: ./.env
#    networks:
#      - stellar
#    ports:
#      - 11625:11625
#      - 11626:11626
#    volumes:
#      - stellar-data:/var/stellar-core
#    healthcheck:
#      test: "CMD /healthcheck.sh"
#    restart: unless-stopped

  stellar:
    image: stellar/quickstart
    command: ["--testnet"]
    networks:
      - stellar
    ports:
      - 8000:8000
    volumes:
      - stellar-data:/opt/stellar:delegated

  eth:
    image: ethereum/client-go
    networks:
      - ethereum
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - ethereum-data:/root
    command: ["--${NETWORK}", "--rpc", "--rpcaddr", "0.0.0.0", "--cache", "512", "--fast", "--metrics"]
    healthcheck:
      test: "geth --exec 'net.version' attach http://localhost:8545"

  bitcoin:
    image: nebolsin/bitcoin-rpc
    env_file: ./.env
    networks:
      - bitcoin
    ports:
      - 8332:8332
      - 8333:8333
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin

  bifrost:
    build: ./bifrost
    env_file: ./.env
    networks:
      - bitcoin
      - ethereum
      - stellar
    links:
      - stellar
      - eth
      - bitcoin
    ports:
      - 9000:9000
    restart: unless-stopped


networks:
  stellar:
  ethereum:
  bitcoin:

volumes:
  bitcoin-data:
  ethereum-data:
  stellar-data:
